### ISSUE TITLE
组件封装

### ISSUE THREAD

**Issue by MaxMooc** [tomfriwel/welCropper#1]
您好，不知能否将welcropper 封装成 wepy  格式的组件，这样大家可直接调用，感谢！

**Comment by tomfriwel** [comment]
@MaxMooc 恩，试试。

**Comment by callmesoul** [comment]
我在封装了

**Comment by callmesoul** [comment]
封装好了
[wepy版本](https://github.com/callmesoul/wepy-corpper)

**Comment by tomfriwel** [comment]
@callmesoul 我可以在readme里面加上你封装的wepy版本的连接吧？

**Comment by callmesoul** [comment]
@tomfriwel why not?
