### ISSUE TITLE
截图完的图片不清晰，文字变模糊

### ISSUE THREAD

**Issue by wengxianxun** [tomfriwel/welCropper#13]
截图完的图片不清晰，文字变模糊

**Comment by tomfriwel** [comment]
@wengxianxun 看看选没选原图

**Comment by wengxianxun** [comment]
sizeType: ['original', 'compressed'] 默认两个都选就会模糊，
sizeType: ['original'] 如果只选一个就清晰

**Comment by tomfriwel** [comment]
@wengxianxun `['original', 'compressed']`你截图的时候下面有个可以选择是否是原图的按钮
<img width="239" alt="screen shot 2018-07-04 at 15 11 39" src="https://user-images.githubusercontent.com/11268235/42262032-97a9be04-7f9c-11e8-913c-16ae57e8854b.png">
