### ISSUE TITLE
请问下为什么选原图 图片会比原图大很多

### ISSUE THREAD

**Issue by thedownup** [tomfriwel/welCropper#17]

**Comment by tomfriwel** [comment]
你是说截图保存后的图片比原图大很多吗？

**Comment by thedownup** [comment]
> 你是说截图保存后的图片比原图大很多吗？

对

**Comment by tomfriwel** [comment]
你可以试试把`wx.canvasToTempFilePath`接口的`fileType`参数设置为`jpg`，它默认导出图片为`png`格式，`png`一般是比`jpg`格式的图片大的。

如果还是不行，这个就跟微信canvas处理有关了。

微信官方文档：[wx.canvasToTempFilePath(Object object, Object this)](https://developers.weixin.qq.com/miniprogram/dev/api/wx.canvasToTempFilePath.html)
