### ISSUE TITLE
拍照后图片不显示

### ISSUE THREAD

**Issue by mrcaopengweiisagoodman** [tomfriwel/welCropper#18]
大佬，你好；ios拍照之后，图片没有显示，且相机没有关闭，这个是什么情况呢?谢谢！

**Comment by tomfriwel** [comment]
重启微信呢？不知道是不是内存方面的原因。

**Comment by mrcaopengweiisagoodman** [comment]
也是那样子的；拍照之后插件启动了，只有裁剪区域的边框，中间没有图片

**Comment by tomfriwel** [comment]
你试试把`maxLength`改小一点试试；或者把`wx.chooseImage`的图片显示出来看看。
