### ISSUE TITLE
大佬canvas可以截屏吗

### ISSUE THREAD

**Issue by kiyosunsun** [tomfriwel/welCropper#21]
我想做一个类似QQ或者微信的发送位置的功能，地图选点之后截取地图，然后canvas做一些事情，请问怎么截取页面中的地图？

**Comment by tomfriwel** [comment]
你可以阅读下官方文档画布和地图这一块，或者直接搜一下看有没有。据我前段时间所知没有，不知道后续有没有更新出这方面的功能。
