### ISSUE TITLE
图片大的情况下导致小程序自动关闭

### ISSUE THREAD

**Issue by lb0726** [tomfriwel/welCropper#6]
图片大的情况下导致小程序自动关闭

**Comment by tomfriwel** [comment]
@lb0726 多大的图？机型？小程序直接崩溃了？

**Comment by lb0726** [comment]
58690327 QQ请教一下

**Comment by lb0726** [comment]
你的QQ是多少？ 我加你

**Comment by tomfriwel** [comment]
@lb0726 不加QQ，有什么问题直接在这里提出来就行了，也方便其他遇到同样问题得人查看。

**Comment by lb0726** [comment]
测试了 小米5s plus 和苹果6 plus 图片有4.05M

**Comment by tomfriwel** [comment]
@lb0726 打开图片的时候就崩了还是点击完成的时候？

**Comment by lb0726** [comment]
@tomfriwel 打开图片

**Comment by tomfriwel** [comment]
如果对图片质量没有太大要求的话，有一个临时解决方案，使用压缩的图片。
```
 wx.chooseImage({
    count: 1,
    sizeType: ['compressed'], // 可以指定是原图还是压缩图，默认二者都有
    sourceType: ['album', 'camera'], // 可以指定来源是相册还是相机，默认二者都有
    success(res) {
})
```

**Comment by lb0726** [comment]
已经在我的小程序里面用上了。
还发现一个问题，就是裁剪的时候拉四个角的有时候开始拉不动，然后拉了好久之后又突然又能拉动了。这种情况下右上角还是拉不动。其它3个角可以。
安卓 小米5s plus和苹果6都出现过

**Comment by tomfriwel** [comment]
真机现在的确有问题，会出现位置错乱，之前都没有出现过，开发工具里是正常的，在看。
<img width="300" alt="screen shot 2018-02-09 at 10 16 50" src="https://user-images.githubusercontent.com/11268235/36008514-8cb25f42-0d82-11e8-898c-faa17e4102e9.png"> <img width="300" alt="screen shot 2018-02-09 at 10 16 50" src="https://user-images.githubusercontent.com/11268235/36008532-aac9aa94-0d82-11e8-9e72-645ad023b227.png">

**Comment by lb0726** [comment]
还有就是选择框同样大小的情况下，上传不同的图片截出来的图片大小不一致

**Comment by tomfriwel** [comment]
截出图片大小本来就是由图片本身大小决定的。跟截图框没关系。

**Comment by tomfriwel** [comment]
官方文档中提到过一点：
`bug: 避免设置过大的宽高，在安卓下会有crash的问题`

**Comment by Amazing-Z** [comment]
@tomfriwel 你好，我这里也测出了这个bug,出现频率还挺高的，有没有什么办法可以解决或者避免呢

**Comment by tomfriwel** [comment]
我可能会添加一个设置最大分辨率的参数，避免原图分辨率过大导致崩溃。

**Comment by tomfriwel** [comment]
现在加了一个`maxLength`来限制最大长宽，避免图片过大导致崩溃。
