### ISSUE TITLE
component形式可以用吗？

### ISSUE THREAD

**Issue by daffy142434** [tomfriwel/welCropper#7]
component形式可以用吗？没有看到例子，有点懵。建议做一个component形式的例子

**Comment by tomfriwel** [comment]
暂时不能

**Comment by tomfriwel** [comment]
@daffy142434 现在可以用了，你可以查看看页面`componentTest`里是怎么用的。

文档之后更新。

**Comment by tomfriwel** [comment]
真机上的问题修复了，你可以试试最新的。
